### ISSUE TITLE
Current login language

### ISSUE THREAD

**Issue by tulac** [neooblaster/zcl_log_util#16]
Current login language 'EN' does not match main language 'FR'. Select 'Advanced' > 'Open in Main Language'

I get this message when I try to import your project. I don't have FR installed on the system.
Can you help me?
BTW I like your project, works great.
Sorry if this is not good way to ask for help, let me know if I have to remove this.

**Comment by neooblaster** [comment]
Hello @tulac ,

It's the right place to ask for help.
I'm the author of the library and this is the only place where you can ask for support.

I will try to check for initial installation using ABAPGIT to check what can I do.
I would like to switch the main langage to English for a better compatibility.

Give me some time (2/3hours) to check and make adjustements. I will keep you inform when I made some change to try again on your side.

If I encounter issues that would implie taking much more time, I will warn you as well.

**Comment by neooblaster** [comment]
Hello @tulac ,

I succeeded to change the project master language from French to English.
When I developed the library, I entered texts in English so they are in the correct language for you.
However, I did not perform yet French translation. The priority was to allow the installation for you.

Please find below my installation test 

## 1. Online Repository Settings 

![image](https://user-images.githubusercontent.com/22078558/221209302-98f602d0-4754-454f-8748-68dc887aff2b.png)


## 2. Result after clicking pull button to deserialize object & activation 

There is some warning next to the activation of the Table (due to the number of the field composing the key)
This installation test has been done on SAP SAP_BASIS 754

![image](https://user-images.githubusercontent.com/22078558/221209385-1eacc176-3ed5-4884-a123-335a3afaf30a.png)


I hope fixes will work with your system as well.
If you have any questions regarding the library, do not hesitate to open an issue to get support.
I made a "powerfull" library, but that comes with complexity.

Best Regards
Nicolas D.

**Comment by tulac** [comment]
Hi @neooblaster!,

Thank you very much. Your work is amazing.

Kind regards,
Stefan T.

**Comment by neooblaster** [comment]
Hello @tulac ,

I'm really happy to know the fix works 😃
Thank a lot for your message. I hope you will enjoy the Log Util !

Best Regards,
Nicolas D.
